version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
      - BOT_TOKEN=${BOT_TOKEN}
      - PUBLISH_INTERVAL=${PUBLISH_INTERVAL}
      - MONTH_VACANCY_LIMIT=${MONTH_VACANCY_LIMIT}
      - DB_SSL_ENABLED=${DB_SSL_ENABLED}
      - BOT_CONTACTS=${BOT_CONTACTS}
      - MINUTES_BETWEEN_PUBLISHING=${MINUTES_BETWEEN_PUBLISHING}
