version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
      - BOT_TOKEN=${BOT_TOKEN}
      - PUBLISH_INTERVAL=${PUBLISH_INTERVAL}
    depends_on:
      - db

  db:
    image: mongo:7.0.0-rc2-jammy
    restart: always
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - dbdata

volumes:
  dbdata: