version: "3.9"

services:
  api:
    build:
      dockerfile: ./
      context: .
    ports:
      - "3000:3000"
    env_file: .env_docker
    depends_on:
      - db

  db:
    image: mongo:7.0.0-rc2-jammy
    restart: always
    ports:
      - "27017:27017"
    env_file: .env_docker
    volumes:
      - dbdata

volumes:
  dbdata: